### ISSUE TITLE
GEF's te groot

### ISSUE THREAD

**Issue by Mister-Jonas** [breinbaas/cptviewer_issues#1]
Hoi Rob,

de viewer kan maar files tot 200 kB aan. De meeste zijn groter.

Groet
Geert

**Comment by breinbaas** [comment]
solution is to allow up to 500kB, should be enough.

**Comment by Mister-Jonas** [comment]
Hoi Rob,

Ik het is gelukt mijn scherm met foutmelding te fotograferen (zie bijlage). De GEF's die niet lukken zijn bijgevoegd.
Deze zijn overigens allemaal bewerkt om te kunnen converteren naar een geldig IMBRO-XML bestand voor de BRO.
Interessant is inderdaad, dat een 'oude' GEF-file het wel doet (dat is B02-729).

Ik hoop dat je hier wat mee kan.

Groet
Geert

**Comment by Mister-Jonas** [comment]
Het zou nu moeten werken 🙂

Groet!
Rob

(wat nog een mogelijke fout is is als de sondering is voorgegraven dus als je daar ooit nog eens tegenaan loopt of zo'n GEF hebt dan hoor ik t graag!)
________________________________
Van: Veld, Geert in 't ***@***.***>
Verzonden: dinsdag 4 mei 2021 11:27
Aan: 'breinbaas/cptviewer_issues' ***@***.***>; Putten, Rob van ***@***.***>
Onderwerp: Viewer


Hoi Rob,



Ik het is gelukt mijn scherm met foutmelding te fotograferen (zie bijlage). De GEF’s die niet lukken zijn bijgevoegd.

Deze zijn overigens allemaal bewerkt om te kunnen converteren naar een geldig IMBRO-XML bestand voor de BRO.

Interessant is inderdaad, dat een ‘oude’ GEF-file het wel doet (dat is B02-729).



Ik hoop dat je hier wat mee kan.



Groet

Geert

**Comment by breinbaas** [comment]
Upload size increased to 500kB
