### ISSUE TITLE
Foutmeldingen

### ISSUE THREAD

**Issue by Mister-Jonas** [breinbaas/cptviewer_issues#2]
De eerste en belangrijke melding: De viewer laadt maar tot 200 kB. Sommige GEF’s zijn groter.
Bij files die wel klein genoeg zijn krijg ik rare foutmeldingen over het inlezen (wat niet kan), die snel weer uit beeld gaan.

GG

**Comment by breinbaas** [comment]
will get the files that are leading to errors, after that I can debug and fix

**Comment by breinbaas** [comment]
The problem was in the reading of the column and record separators where spaces and escape characters were not removed. Fixed with the appropriate code.
